language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - build-tools-27.0.3
    - android-24
  licenses:
    - 'android-sdk-license-.+'
    - '.+'

before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-24"
